### ISSUE TITLE
OSError：Error no file named model_index.json found in directory ../checkpoints/ootd.

### ISSUE THREAD

**Issue by Hankerlove** [levihsu/OOTDiffusion#117]
Traceback (most recent call last):
  File "E:\BUPT-course\VTON\OOTDiffusion\run\run_ootd.py", line 47, in <module>
    model = OOTDiffusionHD(args.gpu_id)
  File "E:\BUPT-course\VTON\OOTDiffusion\ootd\inference_ootd_hd.py", line 56, in __init__
    self.pipe = OotdPipeline.from_pretrained(
  File "C:\Users\86187\.conda\envs\ootd\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1111, in from_pretrained
    config_dict = cls.load_config(cached_folder)
  File "C:\Users\86187\.conda\envs\ootd\lib\site-packages\diffusers\configuration_utils.py", line 365, in load_config
    raise EnvironmentError(
OSError: Error no file named model_index.json found in directory ../checkpoints/ootd.

**Comment by levihsu** [comment]
Please check if the checkpoints are correctly downloaded.
