### ISSUE TITLE
parsing_atr.onnx failed:Protobuf parsing failed.

### ISSUE THREAD

**Issue by keloniton** [levihsu/OOTDiffusion#118]
Hi. I get the following error. Any one to help? I will really appreciate it . Thanks @levihsu @ShineChen1024 @T-Gu 
Traceback (most recent call last):
  File "/home/jovyan/workspace/OOTDiffusion/run/run_ootd.py", line 30, in <module>
    parsing_model = Parsing(args.gpu_id)
  File "/home/jovyan/workspace/OOTDiffusion/preprocess/humanparsing/run_parsing.py", line 20, in __init__
    self.session = ort.InferenceSession(os.path.join(Path(__file__).absolute().parents[2].absolute(), 'checkpoints/humanparsing/parsing_atr.onnx'),
  File "/opt/saturncloud/envs/saturn/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/opt/saturncloud/envs/saturn/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 472, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /home/jovyan/workspace/OOTDiffusion/checkpoints/humanparsing/parsing_atr.onnx failed:Protobuf parsing failed.

**Comment by T-Gu** [comment]
@keloniton Please check your downloaded onnx models, e.g. compare the file size with the original.

**Comment by Rumois** [comment]
> @keloniton请检查您下载的 onnx 模型，例如将文件大小与原始文件大小进行比较。

Where to download onnx models

**Comment by levihsu** [comment]
> re to download onnx models

https://huggingface.co/levihsu/OOTDiffusion/tree/main/checkpoints/humanparsing
