### ISSUE TITLE
/content/OOTDiffusion/checkpoints/humanparsing/parsing_atr.onnx failed. File doesn't exist

### ISSUE THREAD

**Issue by Jaynls** [levihsu/OOTDiffusion#145]
2024-04-02 06:54:15.500603: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-02 06:54:15.500659: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-02 06:54:15.502146: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-04-02 06:54:16.825895: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/OOTDiffusion/run/gradio_ootd.py", line 21, in <module>
    parsing_model_hd = Parsing(0)
  File "/content/OOTDiffusion/preprocess/humanparsing/run_parsing.py", line 20, in __init__
    self.session = ort.InferenceSession(os.path.join(Path(__file__).absolute().parents[2].absolute(), 'checkpoints/humanparsing/parsing_atr.onnx'),
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 452, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from /content/OOTDiffusion/checkpoints/humanparsing/parsing_atr.onnx failed:Load model /content/OOTDiffusion/checkpoints/humanparsing/parsing_atr.onnx failed. File doesn't exist

i am new to computer vision can you help me it showing that parsing_atr.onnx  file doesn't exist.
It will be great if you could help me to solve this issue i am running your code on google colab please refer below pdf.

[screencapture-colab-research-google-drive-1jfFR3QZOn7640Y96zAnHY8wXMki7tq6Q-2024-04-02-17_16_11.pdf](https://github.com/levihsu/OOTDiffusion/files/14836051/screencapture-colab-research-google-drive-1jfFR3QZOn7640Y96zAnHY8wXMki7tq6Q-2024-04-02-17_16_11.pdf)

**Comment by levihsu** [comment]
Hi. You need to download the model checkpoints from https://huggingface.co/levihsu/OOTDiffusion

**Comment by johndpope** [comment]
![Screenshot from 2024-04-14 22-00-29](https://github.com/levihsu/OOTDiffusion/assets/289994/83703254-7fff-448e-8eef-ed6657085f72)
consider adding to readme - had to dig through closed issues to find this.
it did mention clip-vit-large-patch14  but not this one.

**Comment by levihsu** [comment]
> ![Screenshot from 2024-04-14 22-00-29](https://private-user-images.githubusercontent.com/289994/322271197-83703254-7fff-448e-8eef-ed6657085f72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwOTY5ODEsIm5iZiI6MTcxMzA5NjY4MSwicGF0aCI6Ii8yODk5OTQvMzIyMjcxMTk3LTgzNzAzMjU0LTdmZmYtNDQ4ZS04ZWVmLWVkNjY1NzA4NWY3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNFQxMjExMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNWU4ZGZjOTBiYTM5MGJlZWZkOTYzMGJkMWRhZjNlMmI4YzExNTcyNTUwODRiMDZkNWQ5ZmE2MWQwNGI5MjVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.31CvlDn4oDMsl617Q_bseYf_fJHaSx2iULMYAG9oW0I) consider adding to readme - had to dig through closed issues to find this. it did mention clip-vit-large-patch14 but not this one.

Of course mentioned in readme...
<img width="865" alt="image" src="https://github.com/levihsu/OOTDiffusion/assets/33045876/ecd2c42b-83d5-4ddc-9f90-5393039819ec">

**Comment by johndpope** [comment]
where it says - **Please download clip...** - that should say" and OOTDiffusion models" into checkpoints folder.

**Comment by levihsu** [comment]
> where it says - **Please download clip...** - that should say" and OOTDiffusion models" into checkpoints folder.

Updated readme to make it clearer. Thanks for your suggestion.

**Comment by riyachaturvedi413** [comment]
I am getting the issue that parsing_atr.onnx does not exist plzz guide me
