### ISSUE TITLE
/content/OOTDiffusion-train/checkpoints/humanparsing/parsing_atr.onnx failed. File doesn't exist

### ISSUE THREAD

**Issue by Jaynls** [levihsu/OOTDiffusion#146]
2024-04-02 11:53:33.192236: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-02 11:53:33.192368: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-02 11:53:33.309544: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-04-02 11:53:36.148611: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/usr/local/lib/python3.10/dist-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Downloading: "https://huggingface.co/lllyasviel/Annotators/resolve/main/body_pose_model.pth" to /content/OOTDiffusion-train/checkpoints/openpose/ckpts/body_pose_model.pth

100% 200M/200M [00:00<00:00, 234MB/s]
Traceback (most recent call last):
  File "/content/OOTDiffusion-train/run/gradio_ootd.py", line 21, in <module>
    parsing_model_hd = Parsing(0)
  File "/content/OOTDiffusion-train/preprocess/humanparsing/run_parsing.py", line 20, in __init__
    self.session = ort.InferenceSession(os.path.join(Path(__file__).absolute().parents[2].absolute(), 'checkpoints/humanparsing/parsing_atr.onnx'),
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 452, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from /content/OOTDiffusion-train/checkpoints/humanparsing/parsing_atr.onnx failed:Load model /content/OOTDiffusion-train/checkpoints/humanparsing/parsing_atr.onnx failed. File doesn't exist.

Great work and thanks for sharing the code. i am trying to run this code google collab but i am getting following error. It's a basic question i am new to computer vision . I would appreciate if you could help me out to run this repository. Below i am attaching my collab notebook for your reference.

i am getting parsing_atr.onnx file doesn't exist.
[screencapture-colab-research-google-drive-1jfFR3QZOn7640Y96zAnHY8wXMki7tq6Q-2024-04-02-17_16_11.pdf](https://github.com/levihsu/OOTDiffusion/files/14846832/screencapture-colab-research-google-drive-1jfFR3QZOn7640Y96zAnHY8wXMki7tq6Q-2024-04-02-17_16_11.pdf)

**Comment by 7iFinalBoSS** [comment]
hey you have to download those model and place them into the directory, all though you can use this repo to run on colab
https://github.com/7iFinalBoSS/oot_lower_body.git

**Comment by LunaBright** [comment]
I have the same problem as you. Have you solved it? Where did you download parsing_atr.onnx？

**Comment by levihsu** [comment]
@LunaBright https://huggingface.co/levihsu/OOTDiffusion/tree/main/checkpoints/humanparsing
