### ISSUE TITLE
python3.10/site-packages/torch/serialization.py", line 1033, in _legacy_load     magic_number = pickle_module.load(f, **pickle_load_args) _pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by xaviSalazar** [levihsu/OOTDiffusion#163]
**I copied checkpoints from here** ### https://huggingface.co/levihsu/OOTDiffusion/tree/main **but it does not work** 

Traceback (most recent call last):
  File "/home/salazar/OOTDiffusion/run/run_ootd.py", line 29, in <module>
    openpose_model = OpenPose(args.gpu_id)
  File "/home/salazar/OOTDiffusion/preprocess/openpose/run_openpose.py", line 33, in __init__
    self.preprocessor = OpenposeDetector()
  File "/home/salazar/OOTDiffusion/preprocess/openpose/annotator/openpose/__init__.py", line 63, in __init__
    self.body_estimation = Body(body_modelpath)
  File "/home/salazar/OOTDiffusion/preprocess/openpose/annotator/openpose/body.py", line 26, in __init__
    model_dict = util.transfer(self.model, torch.load(model_path))
  File "/home/salazar/OOTDiffusion/env/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/salazar/OOTDiffusion/env/lib/python3.10/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by xaviSalazar** [comment]
Solution found here: Should of used git lfs
https://stackoverflow.com/questions/33049688/what-causes-the-error-pickle-unpicklingerror-invalid-load-key
