### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by wbsljy** [levihsu/OOTDiffusion#171]
一开始运行.gradio_ootd.py文件时可以正常出现并访问本地web但无法生成图片，后面重新运行后直接报错：
(ootd) D:\OOTDiffusion\run>python gradio_ootd.py
Traceback (most recent call last):
  File "D:\OOTDiffusion\run\gradio_ootd.py", line 20, in <module>
    openpose_model_hd = OpenPose(0)
  File "D:\OOTDiffusion\preprocess\openpose\run_openpose.py", line 32, in __init__
    torch.cuda.set_device(gpu_id)
  File "C:\anaconda3\envs\ootd\lib\site-packages\torch\cuda\__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

**Comment by levihsu** [comment]
Please install the cuda version of pytorch
