### ISSUE TITLE
OSError: pretrained_model_name_or_path is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models' If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login`.

### ISSUE THREAD

**Issue by Eminem-lamar** [levihsu/OOTDiffusion#188]
在Windows上，把checkpoints的文件都下载全了，但是输入
PS E:\Clothing\OOTDiffusion-main\OOTDiffusion-main\run> python run_ootd.py --model_path E:/Clothing/OOTDiffusion-main/OOTDiffusion-main/run/examples/model/05997_00.jpg --cloth_path E:/Clothing/OOTDiffusion-main/OOTDiffusion-main/run/examples/garment/00055_00.jpg --scale 2.0 --sample 2
报错如下：
E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Traceback (most recent call last):
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\huggingface_hub\utils\_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/pretrained_model_name_or_path/resolve/main/vae/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\diffusers\configuration_utils.py", line 371, in load_config
    config_file = hf_hub_download(
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\huggingface_hub\file_download.py", line 1221, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\huggingface_hub\file_download.py", line 1325, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\huggingface_hub\file_download.py", line 1823, in _raise_on_head_call_error
    raise head_call_error
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\huggingface_hub\file_download.py", line 1722, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(url=url, proxies=proxies, timeout=etag_timeout, headers=headers)
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\huggingface_hub\file_download.py", line 1645, in get_hf_file_metadata
    r = _request_wrapper(
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\huggingface_hub\file_download.py", line 372, in _request_wrapper
    response = _request_wrapper(
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\huggingface_hub\file_download.py", line 396, in _request_wrapper
    hf_raise_for_status(response)
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\huggingface_hub\utils\_errors.py", line 352, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-665563c1-15b058644d68e50a2434f8de;44740777-b995-40d8-b233-ebd560f3954a)

Repository Not Found for url: https://huggingface.co/pretrained_model_name_or_path/resolve/main/vae/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Clothing\OOTDiffusion-main\OOTDiffusion-main\run\run_ootd.py", line 47, in <module>
    model = OOTDiffusionHD(args.gpu_id)
  File "E:\Clothing\OOTDiffusion-main\OOTDiffusion-main\ootd\inference_ootd_hd.py", line 37, in __init__
    vae = AutoencoderKL.from_pretrained(
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\diffusers\models\modeling_utils.py", line 712, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\diffusers\configuration_utils.py", line 385, in load_config
    raise EnvironmentError(
OSError: pretrained_model_name_or_path is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login`.

**Comment by levihsu** [comment]
Huggingface文件如果是手动一个个点击下载的话估计文件名会有问题 需要核对一下
https://github.com/levihsu/OOTDiffusion/issues/82#issuecomment-1975955294

**Comment by Eminem-lamar** [comment]
您发给我的信件已经收到，祝生活愉快！——陈炜

**Comment by Eminem-lamar** [comment]
> Huggingface文件如果是手动一个个点击下载的话估计文件名会有问题 需要核对一下 [#82 (comment)](https://github.com/levihsu/OOTDiffusion/issues/82#issuecomment-1975955294)

已经检查了一遍文件名，发现没有问题，仍然会报这个错误：
E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Traceback (most recent call last):
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\huggingface_hub\utils\_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/pretrained_model_name_or_path/resolve/main/vae/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\diffusers\configuration_utils.py", line 371, in load_config
    config_file = hf_hub_download(
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\huggingface_hub\file_download.py", line 1221, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\huggingface_hub\file_download.py", line 1325, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\huggingface_hub\file_download.py", line 1823, in _raise_on_head_call_error
    raise head_call_error
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\huggingface_hub\file_download.py", line 1722, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(url=url, proxies=proxies, timeout=etag_timeout, headers=headers)
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\huggingface_hub\file_download.py", line 1645, in get_hf_file_metadata
    r = _request_wrapper(
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\huggingface_hub\file_download.py", line 372, in _request_wrapper
    response = _request_wrapper(
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\huggingface_hub\file_download.py", line 396, in _request_wrapper
    hf_raise_for_status(response)
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\huggingface_hub\utils\_errors.py", line 352, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-6655c611-01dcad1c521387d5459b4a0c;1342d2f8-1795-471f-a8e8-6ca34117d7fe)

Repository Not Found for url: https://huggingface.co/pretrained_model_name_or_path/resolve/main/vae/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Clothing\OOTDiffusion-main\OOTDiffusion-main\run\run_ootd.py", line 47, in <module>
    model = OOTDiffusionHD(args.gpu_id)
  File "E:\Clothing\OOTDiffusion-main\OOTDiffusion-main\ootd\inference_ootd_hd.py", line 37, in __init__
    vae = AutoencoderKL.from_pretrained(
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\diffusers\models\modeling_utils.py", line 712, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "E:\ProgramData\anaconda3\envs\ootd\lib\site-packages\diffusers\configuration_utils.py", line 385, in load_config
    raise EnvironmentError(
OSError: pretrained_model_name_or_path is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login`.

**Comment by Eminem-lamar** [comment]
是不是 configuration_utils.py 中的 pretrained_model_name_or_path 要改成自己的呀，还是其他的哪里出错了 @levihsu

**Comment by nitinmukesh** [comment]
@Eminem-lamar 

How did you solved this issue
