### ISSUE TITLE
INVALID_PROTOBUF

### ISSUE THREAD

**Issue by rohit22059** [levihsu/OOTDiffusion#189]
Traceback (most recent call last):
  File "/home/****/Downloads/cloth_try_on/OOTDiffusion/run/run_ootd.py", line 30, in <module>
    parsing_model = Parsing(args.gpu_id)
  File "/home/****/Downloads/cloth_try_on/OOTDiffusion/preprocess/humanparsing/run_parsing.py", line 20, in __init__
    self.session = ort.InferenceSession(os.path.join(Path(__file__).absolute().parents[2].absolute(), 'checkpoints/humanparsing/parsing_atr.onnx'),
  File "/home/****/anaconda3/envs/ootd/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/****/anaconda3/envs/ootd/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 452, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /home/****/Downloads/cloth_try_on/OOTDiffusion/checkpoints/humanparsing/parsing_atr.onnx failed:Protobuf parsing failed.

Could you pls help to resolve this issue?
Thanks

**Comment by levihsu** [comment]
Please download the checkpoints from https://huggingface.co/levihsu/OOTDiffusion/tree/main/checkpoints

**Comment by harinandyala4** [comment]
2024-06-23 09:11:11.163291: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-06-23 09:11:11.163344: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-06-23 09:11:11.164840: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-06-23 09:11:12.308525: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/OOTDiffusion/run/run_ootd.py", line 30, in <module>
    parsing_model = Parsing(args.gpu_id)
  File "/content/OOTDiffusion/preprocess/humanparsing/run_parsing.py", line 20, in __init__
    self.session = ort.InferenceSession(os.path.join(Path(__file__).absolute().parents[2].absolute(), 'checkpoints/humanparsing/parsing_atr.onnx'),
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 452, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /content/OOTDiffusion/checkpoints/humanparsing/parsing_atr.onnx failed:Protobuf parsing failed.

I am trying this in colab with GPU and facing above issue, Also tried to replace the parsing files from the below location and still the same issue, Could you please guide further. Thanks  

 https://huggingface.co/levihsu/OOTDiffusion/tree/main/checkpoints
