### ISSUE TITLE
报错：缺少文件，但是在项目仓库里找不到相应的文件

### ISSUE THREAD

**Issue by 2681248863** [levihsu/OOTDiffusion#211]
Traceback (most recent call last):
  File "/home/srp/ootd/OOTDiffusion/run/gradio_ootd.py", line 22, in <module>
    ootd_model_hd = OOTDiffusionHD(0)
  File "/home/srp/ootd/OOTDiffusion/ootd/inference_ootd_hd.py", line 37, in __init__
    vae = AutoencoderKL.from_pretrained(
  File "/home/srp/miniconda3/envs/ootd/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 712, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "/home/srp/miniconda3/envs/ootd/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 365, in load_config
    raise EnvironmentError(
OSError: Error no file named config.json found in directory ../checkpoints/ootd.
报错说我在ootd文件夹里少了个config.json，但是我在这个项目的仓库里没看到这个文件可供下载

**Comment by nitinmukesh** [comment]
@2681248863 

How did you solved this issue.
