### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by dastan1910** [levihsu/OOTDiffusion#214]
```
Traceback (most recent call last):
  File "/home/dastan/dastan/my_projects/OOTDiffusion/run/gradio_ootd.py", line 20, in <module>
    openpose_model_hd = OpenPose(0)
  File "/home/dastan/dastan/my_projects/OOTDiffusion/preprocess/openpose/run_openpose.py", line 33, in __init__
    self.preprocessor = OpenposeDetector()
  File "/home/dastan/dastan/my_projects/OOTDiffusion/preprocess/openpose/annotator/openpose/__init__.py", line 63, in __init__
    self.body_estimation = Body(body_modelpath)
  File "/home/dastan/dastan/my_projects/OOTDiffusion/preprocess/openpose/annotator/openpose/body.py", line 26, in __init__
    model_dict = util.transfer(self.model, torch.load(model_path))
  File "/home/dastan/.virtualenvs/oot_diffision/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/dastan/.virtualenvs/oot_diffision/lib/python3.10/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

what do i need?

**Comment by psaren** [comment]
How did you solved this problem?
