### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by Aadik1ng** [levihsu/OOTDiffusion#216]
(venv) PS D:\OOTD\OOTDiffusion> .\venv\Scripts\python.exe .\run\gradio_ootd.py
Traceback (most recent call last):
  File "D:\OOTD\OOTDiffusion\run\gradio_ootd.py", line 20, in <module>
    openpose_model_hd = OpenPose(0)
                        ^^^^^^^^^^^
  File "D:\OOTD\OOTDiffusion\preprocess\openpose\run_openpose.py", line 33, in __init__
    self.preprocessor = OpenposeDetector()
                        ^^^^^^^^^^^^^^^^^^
  File "D:\OOTD\OOTDiffusion\preprocess\openpose\annotator\openpose\__init__.py", line 63, in __init__
    self.body_estimation = Body(body_modelpath)
                           ^^^^^^^^^^^^^^^^^^^^
  File "D:\OOTD\OOTDiffusion\preprocess\openpose\annotator\openpose\body.py", line 26, in __init__
    model_dict = util.transfer(self.model, torch.load(model_path))
                                           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\OOTD\OOTDiffusion\venv\Lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\OOTD\OOTDiffusion\venv\Lib\site-packages\torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by Aadik1ng** [comment]
clone the repo properly
