### ISSUE TITLE
No module named 'skimage'

### ISSUE THREAD

**Issue by jcplus** [levihsu/OOTDiffusion#23]
I encountered this issue saying *skimage* cannot be found.
```
python run_ootd.py --model_path <examples/model> --cloth_path <examples/garment> --model_type dc --category 2 --scale 2.0 --sample 4
cd: no such file or directory: OOTDiffusion/run
Traceback (most recent call last):
  File "/Users/it6/ootd/run/run_ootd.py", line 9, in <module>
    from preprocess.openpose.run_openpose import OpenPose
  File "/Users/it6/ootd/preprocess/openpose/run_openpose.py", line 20, in <module>
    from preprocess.openpose.annotator.openpose import OpenposeDetector
  File "/Users/it6/ootd/preprocess/openpose/annotator/openpose/__init__.py", line 16, in <module>
    from .hand import Hand
  File "/Users/it6/ootd/preprocess/openpose/annotator/openpose/hand.py", line 10, in <module>
    from skimage.measure import label
ModuleNotFoundError: No module named 'skimage'
```

So I use `pip install skimage` and received below errors:
```
Collecting skimage
  Downloading skimage-0.0.tar.gz (757 bytes)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      
      *** Please install the `scikit-image` package (instead of `skimage`) ***
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

From here I'm  in a deadloop.

**Comment by jeffreyrobeson** [comment]
用pip install scikit-image即可

**Comment by jcplus** [comment]
感谢，安装成功！
但是重新运行遇到了RuntimeError: Ninja is required to load C++ extensions问题

**Comment by jcplus** [comment]
Thanks! This spedific issue is solved.
