### ISSUE TITLE
CUDA_HOME environment variable is not set. Please set it to your CUDA install root

### ISSUE THREAD

**Issue by jcplus** [levihsu/OOTDiffusion#25]
Does that mean Silicon M2 is not supported yet? Just gone through all the way here.

**Comment by jeffreyrobeson** [comment]
(ootd) E:\software\OOTDiffusion\run>python run_ootd.py --model_path E:\software\OOTDiffusion\run\examples\model\ --cloth_path E:\software\OOTDiffusion\run\examples\garment\ --scale 2.0 --sample 4
C:\Users\Administrator\pinokio\bin\miniconda\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py:381: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
Traceback (most recent call last):
  File "E:\software\OOTDiffusion\run\run_ootd.py", line 10, in <module>
    from preprocess.humanparsing.aigc_run_parsing import Parsing
  File "E:\software\OOTDiffusion\preprocess\humanparsing\aigc_run_parsing.py", line 7, in <module>
    from parsing_api import load_atr_model, load_lip_model, inference
  File "E:\software\OOTDiffusion\preprocess\humanparsing\parsing_api.py", line 11, in <module>
    import networks
  File "E:\software\OOTDiffusion\preprocess\humanparsing\networks\__init__.py", line 2, in <module>
    from networks.AugmentCE2P import resnet101
  File "E:\software\OOTDiffusion\preprocess\humanparsing\networks\AugmentCE2P.py", line 22, in <module>
    from modules import InPlaceABNSync
  File "E:\software\OOTDiffusion\preprocess\humanparsing\modules\__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "E:\software\OOTDiffusion\preprocess\humanparsing\modules\bn.py", line 10, in <module>
    from .functions import *
  File "E:\software\OOTDiffusion\preprocess\humanparsing\modules\functions.py", line 11, in <module>
    _backend = load(name="inplace_abn",
  File "C:\Users\Administrator\pinokio\bin\miniconda\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 1306, in load
    return _jit_compile(
  File "C:\Users\Administrator\pinokio\bin\miniconda\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\Administrator\pinokio\bin\miniconda\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 1800, in _write_ninja_file_and_build_library
    extra_ldflags = _prepare_ldflags(
  File "C:\Users\Administrator\pinokio\bin\miniconda\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 1887, in _prepare_ldflags
    extra_ldflags.append(f'/LIBPATH:{_join_cuda_home("lib", "x64")}')
  File "C:\Users\Administrator\pinokio\bin\miniconda\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 2407, in _join_cuda_home
    raise OSError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

**Comment by jeffreyrobeson** [comment]
(ootd) E:\software\OOTDiffusion\run>python run_ootd.py --model_path E:\software\OOTDiffusion\run\examples\model\ --cloth_path E:\software\OOTDiffusion\run\examples\garment\ --scale 2.0 --sample 4
Traceback (most recent call last):
  File "E:\software\OOTDiffusion\run\run_ootd.py", line 10, in <module>
    from preprocess.humanparsing.aigc_run_parsing import Parsing
  File "E:\software\OOTDiffusion\preprocess\humanparsing\aigc_run_parsing.py", line 7, in <module>
    from parsing_api import load_atr_model, load_lip_model, inference
  File "E:\software\OOTDiffusion\preprocess\humanparsing\parsing_api.py", line 11, in <module>
    import networks
  File "E:\software\OOTDiffusion\preprocess\humanparsing\networks\__init__.py", line 2, in <module>
    from networks.AugmentCE2P import resnet101
  File "E:\software\OOTDiffusion\preprocess\humanparsing\networks\AugmentCE2P.py", line 22, in <module>
    from modules import InPlaceABNSync
  File "E:\software\OOTDiffusion\preprocess\humanparsing\modules\__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "E:\software\OOTDiffusion\preprocess\humanparsing\modules\bn.py", line 10, in <module>
    from .functions import *
  File "E:\software\OOTDiffusion\preprocess\humanparsing\modules\functions.py", line 11, in <module>
    _backend = load(name="inplace_abn",
  File "C:\Users\Administrator\pinokio\bin\miniconda\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 1306, in load
    return _jit_compile(
  File "C:\Users\Administrator\pinokio\bin\miniconda\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\Administrator\pinokio\bin\miniconda\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 1800, in _write_ninja_file_and_build_library
    extra_ldflags = _prepare_ldflags(
  File "C:\Users\Administrator\pinokio\bin\miniconda\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 1887, in _prepare_ldflags
    extra_ldflags.append(f'/LIBPATH:{_join_cuda_home("lib", "x64")}')
  File "C:\Users\Administrator\pinokio\bin\miniconda\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 2407, in _join_cuda_home
    raise OSError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

(ootd) E:\software\OOTDiffusion\run>

**Comment by jeffreyrobeson** [comment]
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117

(ootd) E:\software\OOTDiffusion\run>python -c "import torch; print(torch.cuda.is_available())"
True

**Comment by jcplus** [comment]
Forcing cuda? My M2 won't be available in that way.

**Comment by iyume** [comment]
> Forcing cuda? My M2 won't be available in that way.

No,I had tested it on CPU and worked. See: https://github.com/AuroBit/ComfyUI-OOTDiffusion

The most problem that I found when I try to run on CPU is that use float32 instead float16 on CPU.

**Comment by iyume** [comment]
> I've seen the instruction on https://github.com/AuroBit/ComfyUI-OOTDiffusion The issue is it's not only happening on Window but Mac as well.

Try `conda install cuda-nvcc -c nvidia` or `conda install cudatoolkit-dev -c conda-forge`

**Comment by jcplus** [comment]
This is for cuda compatible devices which doesn't work in my case as my device is M2.
