### ISSUE TITLE
OSError: Error no file named config.json found in directory ../checkpoints/ootd/ootd_hd/checkpoint-36000.

### ISSUE THREAD

**Issue by invade-art** [levihsu/OOTDiffusion#27]
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "/root/autodl-tmp/OOTDiffusion/run/run_ootd.py", line 47, in <module>
    model = OOTDiffusionHD(args.gpu_id)
  File "/root/autodl-tmp/OOTDiffusion/ootd/inference_ootd_hd.py", line 61, in __init__
    unet_vton = UNetVton2DConditionModel.from_pretrained(
  File "/root/miniconda3/envs/ootd/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/autodl-tmp/OOTDiffusion/diffusers/src/diffusers/models/modeling_utils.py", line 569, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "/root/miniconda3/envs/ootd/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/autodl-tmp/OOTDiffusion/diffusers/src/diffusers/configuration_utils.py", line 370, in load_config
    raise EnvironmentError(
OSError: Error no file named config.json found in directory ../checkpoints/ootd/ootd_hd/checkpoint-36000.

**Comment by invade-art** [comment]
how to solve it?

**Comment by Sheldongg** [comment]
the writer didnt give the hc model

**Comment by invade-art** [comment]
> the writer didnt give the hc model
/root/autodl-tmp/OOTDiffusion/ootd/inference_ootd_dc.py
VIT_PATH = "../checkpoints/clip-vit-large-patch14"
VAE_PATH = "../checkpoints/ootd"
UNET_PATH = "../checkpoints/ootd/ootd_dc/checkpoint-36000"
MODEL_PATH = "../checkpoints/ootd"

it work!!!
