### ISSUE TITLE
clip-vit-large-patch14 problem

### ISSUE THREAD

**Issue by noteprince** [levihsu/OOTDiffusion#29]
(ootd) D:\OOTDiffusion\OOTDiffusion\run>python run_ootd.py --model_path D:\OOTDiffusion\checkpoints\ootd --cloth_path D:\OOTDiffusion\images\demo.png --scale 2.0 --sample 4
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 7/7 [00:00<00:00, 16.35it/s]
Traceback (most recent call last):
  File "D:\miniconda38\envs\ootd\lib\site-packages\transformers\utils\hub.py", line 389, in cached_file
    resolved_file = hf_hub_download(
  File "D:\miniconda38\envs\ootd\lib\site-packages\huggingface_hub\utils\_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "D:\miniconda38\envs\ootd\lib\site-packages\huggingface_hub\utils\_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '../checkpoints/clip-vit-large-patch14'. Use `repo_type` argument if needed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\OOTDiffusion\OOTDiffusion\run\run_ootd.py", line 47, in <module>
    model = OOTDiffusionHD(args.gpu_id)
  File "D:\OOTDiffusion\OOTDiffusion\ootd\inference_ootd_hd.py", line 78, in __init__
    self.auto_processor = AutoProcessor.from_pretrained(VIT_PATH)
  File "D:\miniconda38\envs\ootd\lib\site-packages\transformers\models\auto\processing_auto.py", line 234, in from_pretrained
    preprocessor_config_file = get_file_from_repo(
  File "D:\miniconda38\envs\ootd\lib\site-packages\transformers\utils\hub.py", line 541, in get_file_from_repo
    return cached_file(
  File "D:\miniconda38\envs\ootd\lib\site-packages\transformers\utils\hub.py", line 454, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: '../checkpoints/clip-vit-large-patch14'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

(ootd) D:\OOTDiffusion\OOTDiffusion\run>

I can't find any about clip-vit-large-patch14 model in your huggingface file. So I download the openai file. but it does't work.

How can I solve this problem?

**Comment by nkTmmT** [comment]
download https://huggingface.co/openai/clip-vit-large-patch14/tree/main all files and put them to 'checkpoints/clip-vit-large-patch14' dir

**Comment by nkTmmT** [comment]
![image](https://github.com/levihsu/OOTDiffusion/assets/33121696/63351d0e-1f47-40fb-9bfe-9a1cfa4182e2)
I also downloaded the model of openai, my directory structure is like this, execute the following command 'python run_ootd.py --model_path /home/ysm/tmmt/OOTDiffusion/run/examples/model/01008_00.jpg --cloth_path /home/ysm/tmmt/OOTDiffusion/run/examples/garment/00055_00.jpg --scale 2.0 --sample 4', and it works fine

**Comment by noteprince** [comment]
It works ,thx so much.

**Comment by Brightest08** [comment]
Where can I download checkpoints/ootd

**Comment by jeffreyrobeson** [comment]
![6525770a8591efc2c21a17f882fd9686](https://github.com/levihsu/OOTDiffusion/assets/132809848/b45092c7-5153-4ad9-8d62-fb2a52cdc514)

**Comment by jeffreyrobeson** [comment]
Which of these two options is correct? Download clip-vit-large-patch14 into checkpoints/ootd or checkpoints?

**Comment by xiyuxiaoxiao** [comment]
(ootd) root@autodl-container-0b184db1e3-f047e3df:~/OOTDiffusion/run# python run_ootd.py --model_path /root/OOTDiffusion/run/examples/model/01008_00.jpg --cloth_path /root/OOTDiffusion/run/examples/garment/00055_00.jpg --scale 2.0 --sample 4
Traceback (most recent call last):
  File "/root/OOTDiffusion/run/run_ootd.py", line 29, in <module>
    openpose_model = OpenPose(args.gpu_id)
  File "/root/OOTDiffusion/preprocess/openpose/run_openpose.py", line 33, in __init__
    self.preprocessor = OpenposeDetector()
  File "/root/OOTDiffusion/preprocess/openpose/annotator/openpose/__init__.py", line 63, in __init__
    self.body_estimation = Body(body_modelpath)
  File "/root/OOTDiffusion/preprocess/openpose/annotator/openpose/body.py", line 26, in __init__
    model_dict = util.transfer(self.model, torch.load(model_path))
  File "/root/miniconda3/envs/ootd/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/envs/ootd/lib/python3.10/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x05'. 

I followed the steps to download it, but when I executed it, it threw an error. Does anyone know why?
