### ISSUE TITLE
ImportError: cannot import name 'CaptionProjection' from 'diffusers.models.embeddings' 

### ISSUE THREAD

**Issue by TigerHH6866** [levihsu/OOTDiffusion#40]
(ootd) root@autodl-container-cf29119c3c-0ecee78c:~/autodl-tmp/OOTDiffusion/run# python gradio_ootd.py
Traceback (most recent call last):
  File "/root/autodl-tmp/OOTDiffusion/run/gradio_ootd.py", line 21, in <module>
    from ootd.inference_ootd_hd import OOTDiffusionHD
  File "/root/autodl-tmp/OOTDiffusion/ootd/inference_ootd_hd.py", line 24, in <module>
    from pipelines_ootd.pipeline_ootd import OotdPipeline
  File "/root/autodl-tmp/OOTDiffusion/ootd/pipelines_ootd/pipeline_ootd.py", line 27, in <module>
    from .unet_vton_2d_condition import UNetVton2DConditionModel
  File "/root/autodl-tmp/OOTDiffusion/ootd/pipelines_ootd/unet_vton_2d_condition.py", line 23, in <module>
    from .unet_vton_2d_blocks import (
  File "/root/autodl-tmp/OOTDiffusion/ootd/pipelines_ootd/unet_vton_2d_blocks.py", line 23, in <module>
    from .transformer_vton_2d import Transformer2DModel
  File "/root/autodl-tmp/OOTDiffusion/ootd/pipelines_ootd/transformer_vton_2d.py", line 29, in <module>
    from diffusers.models.embeddings import CaptionProjection, PatchEmbed
ImportError: cannot import name 'CaptionProjection' from 'diffusers.models.embeddings' (/root/miniconda3/envs/ootd/lib/python3.10/site-packages/diffusers/models/embeddings.py)

**Comment by Nomination-NRB** [comment]
> how to solve it?

pip install diffusers=0.24.0
