### ISSUE TITLE
pickle_module.load(f, **pickle_load_args)

### ISSUE THREAD

**Issue by xiyuxiaoxiao** [levihsu/OOTDiffusion#45]
python run_ootd.py --model_path /root/OOTDiffusion/run/examples/model/01008_00.jpg --cloth_path /root/OOTDiffusion/run/examples/garment/00055_00.jpg --scale 2.0 --sample 4

-:
Traceback (most recent call last):
  File "/root/OOTDiffusion/run/run_ootd.py", line 29, in <module>
    openpose_model = OpenPose(args.gpu_id)
  File "/root/OOTDiffusion/preprocess/openpose/run_openpose.py", line 33, in __init__
    self.preprocessor = OpenposeDetector()
  File "/root/OOTDiffusion/preprocess/openpose/annotator/openpose/__init__.py", line 63, in __init__
    self.body_estimation = Body(body_modelpath)
  File "/root/OOTDiffusion/preprocess/openpose/annotator/openpose/body.py", line 26, in __init__
    model_dict = util.transfer(self.model, torch.load(model_path))
  File "/root/miniconda3/envs/ootd/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/envs/ootd/lib/python3.10/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x05'.

**Comment by LuckyOne09** [comment]
@xiyuxiaoxiao Hello, I am wondering if you fixed the bug.

**Comment by xiyuxiaoxiao** [comment]
no

**Comment by johndpope** [comment]
it's working fine for me - use python 3.11
you did install the requirements.txt ? 
here's my pip freeze.
https://gist.github.com/johndpope/2132ea6acc195ad03b77e5ec61002b2d

![Screenshot from 2024-04-15 15-08-33](https://github.com/levihsu/OOTDiffusion/assets/289994/e9cfbee3-b614-423a-9ebc-31b1be0c3cd2)
