### ISSUE TITLE
模型张量对不上

### ISSUE THREAD

**Issue by zjb2020** [levihsu/OOTDiffusion#6]
ValueError: Trying to set a tensor of shape torch.Size([49408, 768]) in "weight" (which has shape torch.Size([49408, 512])), this look incorrect.

请问大佬这个是什么问题呢

**Comment by zjb2020** [comment]
model_type hd

**Comment by levihsu** [comment]
可以检查一下clip-vit-large-patch14是否下载正确，如果还有问题的话可以把报错完整发上来我看看

**Comment by zjb2020** [comment]
具体的报错是这样的
&nbsp;


张家镔
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yuhao ***@***.***&gt;; 
发送时间: 2024年2月21日(星期三) 下午2:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [levihsu/OOTDiffusion] 模型张量对不上 (Issue #6)





 
可以检查一下clip-vit-large-patch14是否下载正确，如果还有问题的话可以把报错完整发上来我看看

**Comment by zjb2020** [comment]
`fos) (base) root@autodl-container-49d843b6cc-d42bdf18:~/autodl-tmp/OOTDiffusion/run# python run_ootd.py --model_path /root/autodl-tmp/Fooocus-API/examples/imgs/38571708425054_.pic_hd.jpg --cloth_path /root/autodl-tmp/Fooocus-API/examples/imgs/38501708424665_.pic.jpg --model_type hd --category 0 --scale 2.0 --sample 4
Loading pipeline components...:   0%|                                                     | 0/7 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/root/autodl-tmp/OOTDiffusion/run/run_ootd.py", line 47, in <module>
    model = OOTDiffusionHD(args.gpu_id)
  File "/root/autodl-tmp/OOTDiffusion/ootd/inference_ootd_hd.py", line 64, in __init__
    self.pipe = OotdPipeline.from_pretrained(
  File "/root/miniconda3/envs/fos/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1265, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "/root/miniconda3/envs/fos/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 523, in load_sub_model
    loaded_sub_model = load_method(cached_folder, **loading_kwargs)
  File "/root/miniconda3/envs/fos/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3706, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/root/miniconda3/envs/fos/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4116, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/root/miniconda3/envs/fos/lib/python3.10/site-packages/transformers/modeling_utils.py", line 778, in _load_state_dict_into_meta_model
    set_module_tensor_to_device(model, param_name, param_device, **set_module_kwargs)
  File "/root/miniconda3/envs/fos/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 310, in set_module_tensor_to_device
    raise ValueError(
ValueError: Trying to set a tensor of shape torch.Size([49408, 768]) in "weight" (which has shape torch.Size([49408, 512])), this look incorrect.`

**Comment by levihsu** [comment]
问题解决了吗？我们正在排查 是不是文件下载有问题？麻烦反馈一下哈

**Comment by zjb2020** [comment]
已经解决了，我把两个config.json文件混淆了，😂
