### ISSUE TITLE
运行run/gradio_ootd.py 后出现报错：subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by syusama** [levihsu/OOTDiffusion#66]
torch：2.2.1+cu118
系统：Windows11
运行run/gradio_ootd.py后报错
`E:\projects\OOTDiffusion\ootd_env\Lib\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
E:\projects\OOTDiffusion\ootd_env\Lib\site-packages\torch\utils\cpp_extension.py:381: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
��Ϣ: ���ṩ��ģʽ�޷��ҵ��ļ���
Traceback (most recent call last):
  File "E:\projects\OOTDiffusion\OOTDiffusion\run\gradio_ootd.py", line 15, in <module>
    from preprocess.humanparsing.aigc_run_parsing import Parsing
  File "E:\projects\OOTDiffusion\OOTDiffusion\preprocess\humanparsing\aigc_run_parsing.py", line 7, in <module>
    from parsing_api import load_atr_model, load_lip_model, inference
  File "E:\projects\OOTDiffusion\OOTDiffusion\preprocess\humanparsing\parsing_api.py", line 11, in <module>
    import networks
  File "E:\projects\OOTDiffusion\OOTDiffusion\preprocess\humanparsing\networks\__init__.py", line 2, in <module>
    from networks.AugmentCE2P import resnet101
  File "E:\projects\OOTDiffusion\OOTDiffusion\preprocess\humanparsing\networks\AugmentCE2P.py", line 22, in <module>
    from modules import InPlaceABNSync
  File "E:\projects\OOTDiffusion\OOTDiffusion\preprocess\humanparsing\modules\__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "E:\projects\OOTDiffusion\OOTDiffusion\preprocess\humanparsing\modules\bn.py", line 10, in <module>
    from .functions import *
  File "E:\projects\OOTDiffusion\OOTDiffusion\preprocess\humanparsing\modules\functions.py", line 11, in <module>
    _backend = load(name="inplace_abn",
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\projects\OOTDiffusion\ootd_env\Lib\site-packages\torch\utils\cpp_extension.py", line 1306, in load
    return _jit_compile(
           ^^^^^^^^^^^^^
  File "E:\projects\OOTDiffusion\ootd_env\Lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "E:\projects\OOTDiffusion\ootd_env\Lib\site-packages\torch\utils\cpp_extension.py", line 1810, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "E:\projects\OOTDiffusion\ootd_env\Lib\site-packages\torch\utils\cpp_extension.py", line 2238, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "E:\projects\OOTDiffusion\ootd_env\Lib\site-packages\torch\utils\cpp_extension.py", line 2373, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cddev\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cddev\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.`

**Comment by zachysaur** [comment]
(venv) (base) F:\OOTDiffusion-for-windows-main\run>python gradio_ootd.py
F:\OOTDiffusion-for-windows-main\venv\Lib\site-packages\torch\utils\cpp_extension.py:383: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
INFO: Could not find files for the given pattern(s).
Traceback (most recent call last):
  File "F:\OOTDiffusion-for-windows-main\run\gradio_ootd.py", line 15, in <module>
    from preprocess.humanparsing.aigc_run_parsing import Parsing
  File "F:\OOTDiffusion-for-windows-main\preprocess\humanparsing\aigc_run_parsing.py", line 7, in <module>
    from parsing_api import load_atr_model, load_lip_model, inference
  File "F:\OOTDiffusion-for-windows-main\preprocess\humanparsing\parsing_api.py", line 11, in <module>
    import networks
  File "F:\OOTDiffusion-for-windows-main\preprocess\humanparsing\networks\__init__.py", line 2, in <module>
    from networks.AugmentCE2P import resnet101
  File "F:\OOTDiffusion-for-windows-main\preprocess\humanparsing\networks\AugmentCE2P.py", line 22, in <module>
    from modules import InPlaceABNSync
  File "F:\OOTDiffusion-for-windows-main\preprocess\humanparsing\modules\__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "F:\OOTDiffusion-for-windows-main\preprocess\humanparsing\modules\bn.py", line 10, in <module>
    from .functions import *
  File "F:\OOTDiffusion-for-windows-main\preprocess\humanparsing\modules\functions.py", line 11, in <module>
    _backend = load(name="inplace_abn",
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\OOTDiffusion-for-windows-main\venv\Lib\site-packages\torch\utils\cpp_extension.py", line 1308, in load
    return _jit_compile(
           ^^^^^^^^^^^^^
  File "F:\OOTDiffusion-for-windows-main\venv\Lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "F:\OOTDiffusion-for-windows-main\venv\Lib\site-packages\torch\utils\cpp_extension.py", line 1810, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "F:\OOTDiffusion-for-windows-main\venv\Lib\site-packages\torch\utils\cpp_extension.py", line 2242, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "F:\OOTDiffusion-for-windows-main\venv\Lib\site-packages\torch\utils\cpp_extension.py", line 2382, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggrov\anaconda3\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggrov\anaconda3\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

(venv) (base) F:\OOTDiffusion-for-windows-main\run>

**Comment by T-Gu** [comment]
@zachysaur @syusama [https://github.com/levihsu/OOTDiffusion/issues/13#issuecomment-1985131346](url)
