### ISSUE TITLE
Can not run on windows?

### ISSUE THREAD

**Issue by linhcentrio** [levihsu/OOTDiffusion#69]
i try to run on windows but got err with ninja and cl.exe, anybody same too on windows? how to fix it?
`(D:\OOTDiffusion\venv) D:\OOTDiffusion>python run/gradio_ootd.py
Traceback (most recent call last):
  File "D:\OOTDiffusion\venv\lib\site-packages\torch\utils\cpp_extension.py", line 2100, in _run_ninja_build
    subprocess.run(
  File "D:\OOTDiffusion\venv\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\OOTDiffusion\run\gradio_ootd.py", line 15, in <module>
    from preprocess.humanparsing.aigc_run_parsing import Parsing
  File "D:\OOTDiffusion\preprocess\humanparsing\aigc_run_parsing.py", line 7, in <module>
    from parsing_api import load_atr_model, load_lip_model, inference
  File "D:\OOTDiffusion\preprocess\humanparsing\parsing_api.py", line 11, in <module>
    import networks
  File "D:\OOTDiffusion\preprocess\humanparsing\networks\__init__.py", line 2, in <module>
    from networks.AugmentCE2P import resnet101
  File "D:\OOTDiffusion\preprocess\humanparsing\networks\AugmentCE2P.py", line 22, in <module>
    from modules import InPlaceABNSync
  File "D:\OOTDiffusion\preprocess\humanparsing\modules\__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "D:\OOTDiffusion\preprocess\humanparsing\modules\bn.py", line 10, in <module>
    from .functions import *
  File "D:\OOTDiffusion\preprocess\humanparsing\modules\functions.py", line 11, in <module>
    _backend = load(name="inplace_abn",
  File "D:\OOTDiffusion\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1308, in load
    return _jit_compile(
  File "D:\OOTDiffusion\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "D:\OOTDiffusion\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1823, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "D:\OOTDiffusion\venv\lib\site-packages\torch\utils\cpp_extension.py", line 2116, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'inplace_abn': [1/5] CONDA_PREFIX\bin\nvcc --generate-dependencies-with-compile --dependency-output inplace_abn_cuda.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -ID:\OOTDiffusion\venv\lib\site-packages\torch\include -ID:\OOTDiffusion\venv\lib\site-packages\torch\include\torch\csrc\api\include -ID:\OOTDiffusion\venv\lib\site-packages\torch\include\TH -ID:\OOTDiffusion\venv\lib\site-packages\torch\include\THC -ICONDA_PREFIX\include -ID:\OOTDiffusion\venv\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++17 --expt-extended-lambda -c D:\OOTDiffusion\preprocess\humanparsing\modules\src\inplace_abn_cuda.cu -o inplace_abn_cuda.cuda.o
FAILED: inplace_abn_cuda.cuda.o
CONDA_PREFIX\bin\nvcc --generate-dependencies-with-compile --dependency-output inplace_abn_cuda.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -ID:\OOTDiffusion\venv\lib\site-packages\torch\include -ID:\OOTDiffusion\venv\lib\site-packages\torch\include\torch\csrc\api\include -ID:\OOTDiffusion\venv\lib\site-packages\torch\include\TH -ID:\OOTDiffusion\venv\lib\site-packages\torch\include\THC -ICONDA_PREFIX\include -ID:\OOTDiffusion\venv\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++17 --expt-extended-lambda -c D:\OOTDiffusion\preprocess\humanparsing\modules\src\inplace_abn_cuda.cu -o inplace_abn_cuda.cuda.o
CreateProcess failed: The system cannot find the file specified.
[2/5] CONDA_PREFIX\bin\nvcc --generate-dependencies-with-compile --dependency-output inplace_abn_cuda_half.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -ID:\OOTDiffusion\venv\lib\site-packages\torch\include -ID:\OOTDiffusion\venv\lib\site-packages\torch\include\torch\csrc\api\include -ID:\OOTDiffusion\venv\lib\site-packages\torch\include\TH -ID:\OOTDiffusion\venv\lib\site-packages\torch\include\THC -ICONDA_PREFIX\include -ID:\OOTDiffusion\venv\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++17 --expt-extended-lambda -c D:\OOTDiffusion\preprocess\humanparsing\modules\src\inplace_abn_cuda_half.cu -o inplace_abn_cuda_half.cuda.o
FAILED: inplace_abn_cuda_half.cuda.o
CONDA_PREFIX\bin\nvcc --generate-dependencies-with-compile --dependency-output inplace_abn_cuda_half.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -ID:\OOTDiffusion\venv\lib\site-packages\torch\include -ID:\OOTDiffusion\venv\lib\site-packages\torch\include\torch\csrc\api\include -ID:\OOTDiffusion\venv\lib\site-packages\torch\include\TH -ID:\OOTDiffusion\venv\lib\site-packages\torch\include\THC -ICONDA_PREFIX\include -ID:\OOTDiffusion\venv\Include -D_GLIBCXX_ninja: fatal: ReadFile: The handle is invalid.

USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++17 --expt-extended-lambda -c D:\OOTDiffusion\preprocess\humanparsing\modules\src\inplace_abn_cuda_half.cu -o inplace_abn_cuda_half.cuda.o
CreateProcess failed: The system cannot find the file specified.`

**Comment by basakamars** [comment]
download ninja and copy to windows\system32

**Comment by basakamars** [comment]
https://github.com/ninja-build/ninja/releases

**Comment by linhcentrio** [comment]
thank you!
