### ISSUE TITLE
CUDA error: invalid device ordinal (to(self.gpu_id)) onwindows

### ISSUE THREAD

**Issue by linhcentrio** [levihsu/OOTDiffusion#71]
(D:\OOTDiffusion\venv) D:\OOTDiffusion>python run/gradio_ootd.py
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 7/7 [00:00<00:00,  7.06it/s]
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["bos_token_id"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["eos_token_id"]` will be overriden.
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 7/7 [00:01<00:00,  6.68it/s]
Traceback (most recent call last):
  File "D:\OOTDiffusion\run\gradio_ootd.py", line 26, in <module>
    ootd_model_dc = OOTDiffusionDC(1)
  File "D:\OOTDiffusion\ootd\inference_ootd_dc.py", line 66, in __init__
    ).to(self.gpu_id)
  File "D:\OOTDiffusion\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 864, in to
    module.to(device, dtype)
  File "D:\OOTDiffusion\venv\lib\site-packages\torch\nn\modules\module.py", line 1160, in to
    return self._apply(convert)
  File "D:\OOTDiffusion\venv\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "D:\OOTDiffusion\venv\lib\site-packages\torch\nn\modules\module.py", line 833, in _apply
    param_applied = fn(param)
  File "D:\OOTDiffusion\venv\lib\site-packages\torch\nn\modules\module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by levihsu** [comment]
https://github.com/levihsu/OOTDiffusion/issues/43#issuecomment-1960861253
