### ISSUE TITLE
No CUDA runtime is found, using CUDA_HOME

### ISSUE THREAD

**Issue by AiRemastered** [levihsu/OOTDiffusion#84]
(ootd) PS C:\User\Projects\OOTDiffusion\OOTDiffusion\run> python run_ootd.py --model_path ../images/Body --cloth_path ../images/cloth --scale 2.0 --sample 4
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7'
C:\Users\User\anaconda3\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py:360: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
Traceback (most recent call last):
  File "C:\User\Projects\OOTDiffusion\OOTDiffusion\run\run_ootd.py", line 10, in <module>
    from preprocess.humanparsing.aigc_run_parsing import Parsing
  File "C:\User\Projects\OOTDiffusion\OOTDiffusion\preprocess\humanparsing\aigc_run_parsing.py", line 7, in <module>
    from parsing_api import load_atr_model, load_lip_model, inference
  File "C:\User\Projects\OOTDiffusion\OOTDiffusion\preprocess\humanparsing\parsing_api.py", line 11, in <module>
    import networks
  File "C:\User\Projects\OOTDiffusion\OOTDiffusion\preprocess\humanparsing\networks\__init__.py", line 2, in <module>
    from networks.AugmentCE2P import resnet101
  File "C:\User\Projects\OOTDiffusion\OOTDiffusion\preprocess\humanparsing\networks\AugmentCE2P.py", line 22, in <module>
    from modules import InPlaceABNSync
  File "C:\User\Projects\OOTDiffusion\OOTDiffusion\preprocess\humanparsing\modules\__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "C:\User\Projects\OOTDiffusion\OOTDiffusion\preprocess\humanparsing\modules\bn.py", line 10, in <module>
    from .functions import *
  File "C:\User\Projects\OOTDiffusion\OOTDiffusion\preprocess\humanparsing\modules\functions.py", line 11, in <module>
    _backend = load(name="inplace_abn",
  File "C:\Users\User\anaconda3\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 1285, in load
    return _jit_compile(
  File "C:\Users\User\anaconda3\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 1510, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\User\anaconda3\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 1612, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "C:\Users\User\anaconda3\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 2008, in _write_ninja_file_to_build_library
    cuda_flags = common_cflags + COMMON_NVCC_FLAGS + _get_cuda_arch_flags()
  File "C:\Users\User\anaconda3\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 1774, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range

******************

(ootd) PS C:\User\Projects\OOTDiffusion\OOTDiffusion\run> python -c "import torch; print(torch.__version__); print(torch.version.cuda)"
2.0.1+cpu
None
*******************************
(base) PS C:\Users\User> python -c "import torch; print(torch.__version__); print(torch.version.cuda)"
2.1.1+cu118
11.8
(base) PS C:\Users\vivek>

**Comment by maopian2333** [comment]
You installed the cpu version of torch under ootd

**Comment by markehu** [comment]
我在centos7的环境也报这个错误，能帮我看看吗？(ootd) falcon175:/mnt/disk1/work/OOTDiffusion/run# python run_ootd.py --model_path ./examples/model/model_9.png --cloth_path ./examples/garment/053744_1.jpg --model_type dc --category 2 --scale 2.0 --sample 4
No CUDA runtime is found, using CUDA_HOME='/root/anaconda3/envs/ootd'
/root/anaconda3/envs/ootd/lib/python3.10/site-packages/torch/utils/cpp_extension.py:366: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++ 4.8.5) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 5.0 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 5 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
Traceback (most recent call last):
  File "/mnt/disk1/work/OOTDiffusion/run/run_ootd.py", line 10, in <module>
    from preprocess.humanparsing.aigc_run_parsing import Parsing
  File "/mnt/disk1/work/OOTDiffusion/preprocess/humanparsing/aigc_run_parsing.py", line 7, in <module>
    from parsing_api import load_atr_model, load_lip_model, inference
  File "/mnt/disk1/work/OOTDiffusion/preprocess/humanparsing/parsing_api.py", line 11, in <module>
    import networks
  File "/mnt/disk1/work/OOTDiffusion/preprocess/humanparsing/networks/__init__.py", line 2, in <module>
    from networks.AugmentCE2P import resnet101
  File "/mnt/disk1/work/OOTDiffusion/preprocess/humanparsing/networks/AugmentCE2P.py", line 22, in <module>
    from modules import InPlaceABNSync
  File "/mnt/disk1/work/OOTDiffusion/preprocess/humanparsing/modules/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "/mnt/disk1/work/OOTDiffusion/preprocess/humanparsing/modules/bn.py", line 10, in <module>
    from .functions import *
  File "/mnt/disk1/work/OOTDiffusion/preprocess/humanparsing/modules/functions.py", line 11, in <module>
    _backend = load(name="inplace_abn",
  File "/root/anaconda3/envs/ootd/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/root/anaconda3/envs/ootd/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/root/anaconda3/envs/ootd/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1611, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "/root/anaconda3/envs/ootd/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2007, in _write_ninja_file_to_build_library
    cuda_flags = common_cflags + COMMON_NVCC_FLAGS + _get_cuda_arch_flags()
  File "/root/anaconda3/envs/ootd/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1773, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range
(ootd) falcon175:/mnt/disk1/work/OOTDiffusion/run# python -c "import torch; print(torch.version); print(torch.version.cuda)"
<module 'torch.version' from '/root/anaconda3/envs/ootd/lib/python3.10/site-packages/torch/version.py'>
11.7

**Comment by T-Gu** [comment]
@markehu [https://github.com/levihsu/OOTDiffusion/issues/13#issuecomment-1985131346](url)
