### ISSUE TITLE
could not find model [windows]

### ISSUE THREAD

**Issue by Spr-Peach** [levihsu/OOTDiffusion#85]
(ootd) C:\Users\namiachy\OOTDiffusion>python run\gradio_ootd.py
Traceback (most recent call last):
  File "C:\Users\namiachy\miniconda3\envs\ootd\lib\site-packages\diffusers\configuration_utils.py", line 371, in load_config
    config_file = hf_hub_download(
  File "C:\Users\namiachy\miniconda3\envs\ootd\lib\site-packages\huggingface_hub\utils\_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "C:\Users\namiachy\miniconda3\envs\ootd\lib\site-packages\huggingface_hub\utils\_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '../checkpoints/ootd'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\namiachy\OOTDiffusion\run\gradio_ootd.py", line 22, in <module>
    ootd_model_hd = OOTDiffusionHD(0)
  File "C:\Users\namiachy\OOTDiffusion\ootd\inference_ootd_hd.py", line 37, in __init__
    vae = AutoencoderKL.from_pretrained(
  File "C:\Users\namiachy\miniconda3\envs\ootd\lib\site-packages\diffusers\models\modeling_utils.py", line 712, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "C:\Users\namiachy\miniconda3\envs\ootd\lib\site-packages\diffusers\configuration_utils.py", line 407, in load_config
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like ../checkpoints/ootd is not the path to a directory containing a config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.

(ootd) C:\Users\namiachy\OOTDiffusion>

I had downloaded the new ootd-dc model and placed it into ootd folder and the error is still there. please help me how to fix it, thanx a lot

**Comment by Spr-Peach** [comment]
已解决！

**Comment by ShashwatNigam99** [comment]
How did you solve it?
