### ISSUE TITLE
报错如何解决

### ISSUE THREAD

**Issue by sehfdjajsj** [levihsu/OOTDiffusion#89]
Traceback (most recent call last):
  File "/data/oy/OOTDiffusion/run/run_ootd.py", line 47, in <module>
    model = OOTDiffusionHD(args.gpu_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/oy/OOTDiffusion/ootd/inference_ootd_hd.py", line 37, in __init__
    vae = AutoencoderKL.from_pretrained(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/oy/.env/lib/python3.11/site-packages/diffusers/models/modeling_utils.py", line 712, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
                                         ^^^^^^^^^^^^^^^^
  File "/data/oy/.env/lib/python3.11/site-packages/diffusers/configuration_utils.py", line 365, in load_config
    raise EnvironmentError(
OSError: Error no file named config.json found in directory ../checkpoints/ootd.

**Comment by levihsu** [comment]
https://github.com/levihsu/OOTDiffusion/issues/82#issuecomment-1975955294

**Comment by sehfdjajsj** [comment]
ootd这个文件在哪下载哥
