### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by markehu** [levihsu/OOTDiffusion#98]
我在centos下运行报错，请帮忙看看什么原因：
(ootd) falcon175:/mnt/disk1/work/OOTDiffusion/run# python run_ootd.py --model_path ./examples/model/model_9.png --cloth_path ./examples/garment/053744_1.jpg --model_type dc --category 2 --scale 2.0 --sample 4
No CUDA runtime is found, using CUDA_HOME='/root/anaconda3/envs/ootd'
Traceback (most recent call last):
  File "/mnt/disk1/work/OOTDiffusion/run/run_ootd.py", line 10, in <module>
    from preprocess.humanparsing.aigc_run_parsing import Parsing
  File "/mnt/disk1/work/OOTDiffusion/preprocess/humanparsing/aigc_run_parsing.py", line 7, in <module>
    from parsing_api import load_atr_model, load_lip_model, inference
  File "/mnt/disk1/work/OOTDiffusion/preprocess/humanparsing/parsing_api.py", line 11, in <module>
    import networks
  File "/mnt/disk1/work/OOTDiffusion/preprocess/humanparsing/networks/__init__.py", line 2, in <module>
    from networks.AugmentCE2P import resnet101
  File "/mnt/disk1/work/OOTDiffusion/preprocess/humanparsing/networks/AugmentCE2P.py", line 22, in <module>
    from modules import InPlaceABNSync
  File "/mnt/disk1/work/OOTDiffusion/preprocess/humanparsing/modules/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "/mnt/disk1/work/OOTDiffusion/preprocess/humanparsing/modules/bn.py", line 10, in <module>
    from .functions import *
  File "/mnt/disk1/work/OOTDiffusion/preprocess/humanparsing/modules/functions.py", line 11, in <module>
    _backend = load(name="inplace_abn",
  File "/root/anaconda3/envs/ootd/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/root/anaconda3/envs/ootd/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/root/anaconda3/envs/ootd/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1611, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "/root/anaconda3/envs/ootd/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2007, in _write_ninja_file_to_build_library
    cuda_flags = common_cflags + COMMON_NVCC_FLAGS + _get_cuda_arch_flags()
  File "/root/anaconda3/envs/ootd/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1773, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range

torch的版本应该是正确的：
(ootd) falcon175:/mnt/disk1/work/OOTDiffusion/run# python -c "import torch; print(torch.version); print(torch.version.cuda)"
<module 'torch.version' from '/root/anaconda3/envs/ootd/lib/python3.10/site-packages/torch/version.py'>
11.7
(ootd) falcon175:/mnt/disk1/work/OOTDiffusion/run#

**Comment by T-Gu** [comment]
[https://github.com/levihsu/OOTDiffusion/issues/13#issuecomment-1985131346](url)
